AWSTemplateFormatVersion: '2010-09-09'
Description: Creation of an AIM role
Parameters:
  IAMRole1:
    Description: Managed IAM Policy
    Type: String
    Default: Test

Resources:
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
      Tags:
        - Key: Name
          Value: MC-Test-Iam-role

  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: 'S3Access'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - 
            Effect: Allow
            Action: 
              - 's3:ListBucket'
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: 
              - 'arn:aws:s3:::clarkem8-dev-store'
              - 'arn:aws:s3:::clarkem8-dev-store/*'
      Roles: 
        - Ref: "RootRole"

  RootInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - Ref: "RootRole"
        
Outputs:  
  IAMRole:
    Description: IAM role created
    Value:
      Ref: RootRole
