AWSTemplateFormatVersion: 2010-09-09
Description: Creation of a VPC
Parameters:
  VPCCIDR:
    Description: IP Address range for the VPN connected VPC
    Type: String
    Default: 172.31.0.0/16
  
  AZ:
    Type: AWS::EC2::AvailabilityZone::Name
    
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: False
      EnableDnsSupport: True
      Tags: 
        - Key: Name
          Value: MC-Test-VPC

  Subnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 
        Ref: AZ
      CidrBlock: [ "192.168.0.0/24", 6, 5 ]
      Tags: 
        - Key: Name
          Value: MC-Test-Subnet
  VpcId: !Ref VPC
  
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Sample security group
      GroupName: MC-Test-SG
      SecurityGroupIngress:
        Description: Inbound security group rules
        CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
      Tags: 
        - Key: Name
          Value: MC-Test-SG
      VpcId: !Ref VPC

Outputs:
  VPC:
    Description: VPC created
    Value:
      Ref: VPC
  SecurityGroup:
    Description: Securty group created
    Value:
      Ref: SecurityGroup
